### ISSUE TITLE
Uses V8 even when SSE4.2 is available

### ISSUE THREAD

**Issue by stachetheoverlord** [luizperes/simdjson_nodejs#16]
Simdjson also supports SSE4.2 - but this library still falls back to V8's parser when it's available.

**Comment by luizperes** [comment]
Hi @stachetheoverlord, I am not so sure I understood what you described. Do you mean that it falls in the AVX2 when SSE4.2 is available? The `V8` is related to the JS engine that binds the C++ lib, it is not direclty related to simdjson. Could you clarify that and give me repro steps and expected results? Thanks!

**Comment by stachetheoverlord** [comment]
When benchmarking this library on a CPU that does not support AVX2, but does support SSE4.2, it only uses the default (nonavx2) parser.

Simdjson [supports SSE4.2](https://github.com/lemire/simdjson#requirements), so it should be used in that situation

**Comment by luizperes** [comment]
Oh, got it! It should be simply fixed by adding an `&&` to the the preprocessing directives https://github.com/luizperes/simdjson_nodejs/blob/master/simdjson/nonavx2.cpp#L1 adding the case for SSE4.2, I am currently only checking for `AVX2`.
Although, I am quite a bit busy lately and won't have time to do it soon, so feel free to do it, if you feel comfortable.

**Comment by luizperes** [comment]
Hi @stachetheoverlord,
I have just double checked, my projects  is outdated as per https://github.com/luizperes/simdjson_nodejs/issues/15, will try to fix it soon, once I verify a potential problem with the singleheader source file

**Comment by luizperes** [comment]
Done on #19, you can now use it, cheers!
